// Sample data for local testing ONLY (npm run seed / npm run demo).
// The seed script refuses to run with NODE_ENV=production.
// These are public, made-up accounts: never reuse these passwords for
// real accounts, and create the real admin with `npm run create-admin`.

// Dates are relative to today, so the events always look current.
const inDays = (n) => {
  const ymd = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Hebron' }).format(new Date(Date.now() + n * 86400000))
  return new Date(`${ymd}T00:00:00Z`)
}

export const sampleUsers = [
  {
    key: 'admin',
    name: 'مدير الموقع',
    email: 'admin@alasayel.test',
    password: 'Admin@12345',
    phone: '+970 598 895 481',
    role: 'admin',
    note: 'Admin: dashboard, add/edit horses & events, manage tickets',
  },
  {
    key: 'sara',
    name: 'سارة يوسف',
    email: 'sara@alasayel.test',
    password: 'Sara@12345',
    phone: '+970 599 111 222',
    role: 'customer',
    note: 'Customer with tickets: one awaiting payment, one confirmed',
  },
  {
    key: 'khaled',
    name: 'خالد الفارس',
    email: 'khaled@alasayel.test',
    password: 'Khaled@12345',
    phone: '+970 599 333 444',
    role: 'customer',
    note: 'Customer with a free ticket and a past (used) ticket',
  },
  {
    key: 'new',
    name: 'زائر جديد',
    email: 'new@alasayel.test',
    password: 'New@12345',
    phone: '',
    role: 'customer',
    note: 'Customer with no bookings yet',
  },
  {
    key: 'blocked',
    name: 'حساب موقوف',
    email: 'blocked@alasayel.test',
    password: 'Blocked@12345',
    phone: '',
    role: 'customer',
    isActive: false,
    note: 'Deactivated account: login must be refused',
  },
]

// Images come from frontend/public.
export const sampleHorses = [
  {
    name: 'ريم',
    gender: 'mare',
    breed: 'عربي أصيل',
    age: 7,
    color: 'أشهب',
    price: 18000,
    currency: 'USD',
    location: 'أريحا',
    description: 'فرس عربية أصيلة هادئة الطباع، مدربة على العروض.\nمناسبة للفرسان المتوسطين.',
    status: 'available',
    images: ['SwimerHourse.png', 'Compatition.png'],
  },
  {
    name: 'صقر',
    gender: 'stallion',
    breed: 'ثوروبريد',
    age: 5,
    color: 'أدهم',
    price: 45000,
    currency: 'ILS',
    location: 'أريحا',
    description: 'حصان سباق سريع بلياقة عالية.',
    status: 'available',
    images: ['Race.png'],
  },
  {
    name: 'نجمة',
    gender: 'filly',
    breed: 'عربي أصيل',
    age: 2,
    color: 'أشقر',
    price: 9000,
    currency: 'JOD',
    location: 'أريحا',
    description: 'مهرة واعدة من سلالة ممتازة.',
    status: 'pending',
    images: ['Center.png'],
  },
  {
    name: 'برق',
    gender: 'gelding',
    breed: 'وارمبلود',
    age: 11,
    color: 'كميت',
    price: 12000,
    currency: 'USD',
    location: 'أريحا',
    description: 'تم بيعه — مثال على إعلان مُباع.',
    status: 'sold',
    images: ['HomePic.png'],
  },
]

export const sampleEvents = [
  {
    key: 'jumping',
    title: 'بطولة الأصايل لقفز الحواجز',
    date: inDays(12),
    startTime: '15:00',
    endTime: '19:30',
    location: 'ميدان المركز — أريحا',
    ticketPrice: 30,
    currency: 'ILS',
    totalTickets: 250,
    status: 'published',
    description: 'منافسات قفز حواجز لعدة فئات، بمشاركة فرسان من مختلف المناطق.\nالأبواب تفتح قبل ساعة من البداية.',
    cover: 'Compatition.png',
  },
  {
    key: 'race',
    title: 'سباق الخيول العربية الأصيلة',
    date: inDays(5),
    startTime: '16:00',
    endTime: '18:00',
    location: 'مضمار المركز — أريحا',
    ticketPrice: 0,
    currency: 'ILS',
    totalTickets: 400,
    status: 'published',
    description: 'سباق سرعة للخيول العربية الأصيلة. الدخول مجاني مع الحجز المسبق.',
    cover: 'Race.png',
  },
  {
    key: 'lastSeats',
    title: 'ورشة العناية بالخيل',
    date: inDays(8),
    startTime: '10:00',
    endTime: '12:00',
    location: 'إسطبلات المركز',
    ticketPrice: 50,
    currency: 'ILS',
    totalTickets: 12,
    status: 'published',
    description: 'ورشة عملية للمبتدئين — عدد المقاعد محدود جدًا.',
    cover: 'LandscabeTraining.png',
  },
  {
    key: 'family',
    title: 'يوم العائلة',
    date: inDays(25),
    location: 'مركز الأصايل',
    ticketPrice: 20,
    currency: 'ILS',
    totalTickets: 100,
    status: 'closed',
    description: 'مثال على فعالية مغلقة الحجز.',
    cover: 'Children.png',
  },
  {
    key: 'openDay',
    title: 'اليوم المفتوح',
    date: inDays(15),
    startTime: '09:00',
    endTime: '17:00',
    location: 'مركز الأصايل',
    ticketPrice: 0,
    currency: 'ILS',
    totalTickets: 0,
    status: 'published',
    description: 'مثال على فعالية بدخول حر (بدون حجز).',
    cover: 'PresentingLogo.png',
  },
  {
    key: 'beauty',
    title: 'مسابقة جمال الخيل العربي',
    date: inDays(-14),
    startTime: '10:00',
    endTime: '14:00',
    location: 'حلبة العرض — أريحا',
    ticketPrice: 25,
    currency: 'ILS',
    totalTickets: 150,
    status: 'published',
    description: 'مثال على فعالية سابقة.',
    cover: 'PresentingLogo2.png',
  },
  {
    key: 'camp',
    title: 'المخيم الصيفي (مسودة)',
    date: inDays(40),
    location: 'مركز الأصايل',
    ticketPrice: 150,
    currency: 'ILS',
    totalTickets: 30,
    status: 'draft',
    description: 'مثال على مسودة — لا تظهر للزوار.',
    cover: null,
  },
]

// [user key, event key, quantity, status]
export const sampleTickets = [
  ['sara', 'jumping', 3, 'reserved'],
  ['sara', 'race', 2, 'confirmed'],
  ['khaled', 'race', 4, 'confirmed'],
  ['khaled', 'beauty', 2, 'used'],
  ['khaled', 'lastSeats', 10, 'confirmed'], // leaves only 2 seats
]
